env: prod

crypto_input_path: /Volumes/workspace/default/dbx/input/crypto_prices.csv
crypto_input_format: csv
crypto_output_path: /Volumes/workspace/default/dbx/output/prod/crypto_market_analysis

etl_input_path: /Volumes/workspace/default/dbx/input/raw_etl.json
etl_input_format: json
etl_output_path: /Volumes/workspace/default/dbx/output/prod/etl_curated
etl_required_columns:
  - id
  - updated_at
etl_expected_types:
  id: string
etl_dedupe_keys:
  - id
etl_dedupe_order_col: updated_at

stream_output_path: /Volumes/workspace/default/dbx/output/prod/streaming_output
stream_checkpoint_path: /Volumes/workspace/default/dbx/checkpoints/prod/streaming_job
stream_rows_per_second: 10
stream_run_seconds: 60

# S3 bronze ingest job
s3_bronze_output_path: s3a://test-ak-crypto-data-storage/bronze/
s3_ingest_num_hours: 168
